# -*- coding: utf-8 -*-
"""IADataAnalyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GeKbejw-bSvq1FsdIqtE5xsYAKCOxR0

# **AI Data Analyst**

##### **Instalations**
"""

!pip install -q pandas gradio matplotlib openpyxl tabulate langchain-groq numpy

"""##### **Imports and config**"""

import os, json, uuid, math, tempfile, traceback
from typing import Any, Dict, List, Optional

import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import gradio as gr

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage

import os
from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("groq_api_key")

llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

"""##### **Data and Schema**"""

STATE: Dict[str, Any] = {"df": None, "schema": "", "filename": ""}


def load_dataframe(file_path: str) -> pd.DataFrame:
    path_lower = file_path.lower()
    if path_lower.endswith(".csv"):
        try:
            df = pd.read_csv(file_path)
        except UnicodeDecodeError:
            df = pd.read_csv(file_path, encoding="latin1")
    elif path_lower.endswith((".xlsx", ".xls")):
        df = pd.read_excel(file_path)
    else:
        raise ValueError("Unsupported format. Please upload CSV, XLSX, or XLS.")

    if df.empty:
        raise ValueError("The uploaded file is empty.")

    df = df.loc[:, ~df.columns.duplicated()].copy()
    df.columns = [str(c).strip() for c in df.columns]

    for col in df.columns:
        if df[col].dtype == "object":
            sample = df[col].dropna().astype(str).head(20)
            if len(sample) > 0:
                parsed = pd.to_datetime(sample, errors="coerce")
                if parsed.notna().mean() >= 0.6:
                    df[col] = pd.to_datetime(df[col], errors="coerce")
    return df


def build_schema(df: pd.DataFrame) -> str:
    lines = [f"Rows: {len(df)}", f"Columns: {len(df.columns)}", "Schema:"]
    for col in df.columns:
        dtype    = str(df[col].dtype)
        non_null = int(df[col].notna().sum())
        nulls    = int(df[col].isna().sum())
        sample   = df[col].dropna().astype(str).head(5).tolist()
        lines.append(
            f"  - {col} | type={dtype} | non_null={non_null} | nulls={nulls} | sample={sample}"
        )
    num_cols = df.select_dtypes(include="number").columns.tolist()
    cat_cols = df.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
    dt_cols  = df.select_dtypes(include=["datetime64[ns]"]).columns.tolist()
    lines += [
        f"Numeric columns: {num_cols}",
        f"Categorical columns: {cat_cols}",
        f"Date columns: {dt_cols}",
    ]
    return "\n".join(lines)

"""##### **LLM Planner**"""

PLANNER_PROMPT = """You are an expert data analysis planner.
Convert the user's question into an executable JSON plan for a pandas DataFrame.

STRICT RULES:
1. Return ONLY valid JSON. No markdown, no extra text outside the JSON.
2. Use only columns that exist in the provided schema.
3. Choose the MOST APPROPRIATE chart_type based on the semantic context:
   - "bar"       → compare categories or rankings
   - "line"      → time trends or continuous series
   - "pie"       → proportions (max 8 categories)
   - "donut"     → same as pie with more visual style
   - "histogram" → distribution of a numeric variable
   - "scatter"   → relationship/correlation between two numeric variables
   - "box"       → spread and outliers of a numeric variable
   - "area"      → cumulative trend emphasizing volume
   - "heatmap"   → correlation matrix between multiple numeric variables
   - "none"      → when a chart adds no value
4. If the user doesn't explicitly request a chart, pick the most useful one.
5. "by X" → groupby on column X.
6. "distribution / spread" → distribution operation.
7. "correlation / relationship" → correlation operation.
8. "top / best / highest / lowest" → top_n operation.
9. "statistics / describe / summary stats" → full_stats operation.
10. For numbers, DO NOT write it en exponential formmat, just use decimal

Allowed operations: summary, average, sum, count, min, max, median,
                    top_n, groupby_agg, distribution, correlation,
                    list_unique, full_stats

Allowed agg_func: mean, sum, count, min, max, median, std, var

Return EXACTLY this JSON structure:
{
  "operation": "...",
  "target_column": "column_name_or_null",
  "groupby_column": "column_name_or_null",
  "agg_func": "mean|sum|count|min|max|median|std|var|null",
  "top_n": 10,
  "sort_order": "asc|desc|null",
  "filters": [{"column":"col","operator":"==|!=|>|<|>=|<=|contains","value":"val"}],
  "chart_type": "none|bar|line|pie|donut|histogram|scatter|box|area|heatmap",
  "chart_x": "column_name_or_null",
  "chart_y": "column_name_or_null",
  "chart_title": "Descriptive chart title"
}"""


def clean_json(raw: str) -> str:
    text = raw.strip().strip("`")
    if text.lower().startswith("json"):
        text = text[4:].strip()
    first = text.find("{");  last = text.rfind("}")
    if first != -1 and last != -1 and last > first:
        text = text[first:last + 1]
    return text


def get_plan(schema: str, question: str) -> Dict[str, Any]:
    full_prompt = (
        f"{PLANNER_PROMPT}\n\nDataset schema:\n{schema}\n\nUser question:\n{question}"
    )
    resp = llm.invoke([HumanMessage(content=full_prompt)])
    raw  = resp.content if isinstance(resp.content, str) else str(resp.content)
    plan = json.loads(clean_json(raw))
    defaults = {
        "operation": "summary", "target_column": None, "groupby_column": None,
        "agg_func": "mean",     "top_n": 10,           "sort_order": "desc",
        "filters": [],          "chart_type": "none",   "chart_x": None,
        "chart_y": None,        "chart_title": "Analysis",
    }
    for k, v in defaults.items():
        plan.setdefault(k, v)
    return plan

"""##### **Helpers and filters**"""

def fmt(value: Any) -> str:
    if value is None: return "N/A"
    try:
        if isinstance(value, float):
            if math.isnan(value): return "NaN"
            return f"{value:,.4g}"
        if pd.isna(value): return "NaN"
    except Exception:
        pass
    return str(value)


def pick_num(df: pd.DataFrame) -> Optional[str]:
    cols = df.select_dtypes(include="number").columns.tolist()
    return cols[0] if cols else None


def pick_cat(df: pd.DataFrame) -> Optional[str]:
    cols = df.select_dtypes(include=["object", "category", "bool"]).columns.tolist()
    return cols[0] if cols else None


def apply_filters(df: pd.DataFrame, filters: list) -> pd.DataFrame:
    out = df.copy()
    for f in filters or []:
        col = f.get("column"); op = f.get("operator"); val = f.get("value")
        if col not in out.columns: continue
        try:
            s = out[col]
            if op == "==":         out = out[s == val]
            elif op == "!=":       out = out[s != val]
            elif op == "contains": out = out[s.astype(str).str.contains(str(val), case=False, na=False)]
            else:
                num_val = float(val)
                num_s   = pd.to_numeric(s, errors="coerce")
                if   op == ">":  out = out[num_s > num_val]
                elif op == "<":  out = out[num_s < num_val]
                elif op == ">=": out = out[num_s >= num_val]
                elif op == "<=": out = out[num_s <= num_val]
        except Exception:
            continue
    return out

"""##### **Chart Engine**"""

PALETTE = [
    "#10a37f", "#2563eb", "#f59e0b", "#ef4444",
    "#8b5cf6", "#06b6d4", "#ec4899", "#84cc16",
    "#f97316", "#0ea5e9",
]


def setup_light_style():
    plt.rcParams.update({
        "figure.facecolor":  "#ffffff",
        "axes.facecolor":    "#f9fafb",
        "axes.edgecolor":    "#e5e7eb",
        "axes.labelcolor":   "#374151",
        "axes.titlecolor":   "#111827",
        "axes.titlesize":    13,
        "axes.titleweight":  "semibold",
        "axes.titlepad":     14,
        "axes.grid":         True,
        "grid.color":        "#e5e7eb",
        "grid.linewidth":    0.7,
        "grid.alpha":        1.0,
        "xtick.color":       "#6b7280",
        "ytick.color":       "#6b7280",
        "xtick.labelsize":   9,
        "ytick.labelsize":   9,
        "text.color":        "#374151",
        "legend.facecolor":  "#ffffff",
        "legend.edgecolor":  "#e5e7eb",
        "legend.fontsize":   9,
        "font.family":       "DejaVu Sans",
        "figure.dpi":        130,
    })


def save_fig() -> str:
    path = os.path.join(tempfile.gettempdir(), f"chart_{uuid.uuid4().hex[:8]}.png")
    plt.tight_layout(pad=1.8)
    plt.savefig(path, dpi=130, bbox_inches="tight", facecolor="#ffffff")
    plt.close("all")
    return path


def make_chart(
    chart_type: str,
    data: pd.DataFrame,
    x: Optional[str],
    y: Optional[str],
    title: str,
) -> Optional[str]:
    if chart_type == "none" or data is None or data.empty:
        return None

    setup_light_style()

    try:
        # ── BAR ────────────────────────────────────────────
        if chart_type == "bar":
            if x not in data.columns or y not in data.columns: return None
            df2 = data[[x, y]].copy()
            df2[y] = pd.to_numeric(df2[y], errors="coerce")
            df2 = df2.dropna(subset=[y]).head(25)
            if df2.empty: return None
            fig, ax = plt.subplots(figsize=(10, 5))
            colors = [PALETTE[i % len(PALETTE)] for i in range(len(df2))]
            bars = ax.bar(df2[x].astype(str), df2[y], color=colors,
                          edgecolor="white", linewidth=0.6, width=0.62)
            ax.bar_label(bars, fmt="%.4g", padding=3, color="#6b7280", fontsize=8)
            ax.set_xlabel(x, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_ylabel(y, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_title(title, color="#111827", fontsize=13, fontweight="semibold")
            ax.spines[["top", "right"]].set_visible(False)
            ax.spines[["left", "bottom"]].set_color("#e5e7eb")
            plt.xticks(rotation=35, ha="right")
            return save_fig()

        # ── LINE ───────────────────────────────────────────
        elif chart_type == "line":
            if x not in data.columns or y not in data.columns: return None
            df2 = data[[x, y]].copy()
            df2[y] = pd.to_numeric(df2[y], errors="coerce")
            df2 = df2.dropna(subset=[y]).head(200)
            if df2.empty: return None
            fig, ax = plt.subplots(figsize=(10, 5))
            xs = range(len(df2))
            ax.plot(xs, df2[y], color=PALETTE[0], linewidth=2.2,
                    marker="o", markersize=3.5, markerfacecolor="white",
                    markeredgecolor=PALETTE[0], markeredgewidth=1.5)
            ax.fill_between(xs, df2[y], alpha=0.07, color=PALETTE[0])
            ax.set_xlabel(x, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_ylabel(y, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_title(title, color="#111827", fontsize=13, fontweight="semibold")
            step = max(1, len(df2) // 10)
            ax.set_xticks(range(0, len(df2), step))
            ax.set_xticklabels(df2[x].astype(str).iloc[::step], rotation=35, ha="right")
            ax.spines[["top", "right"]].set_visible(False)
            ax.spines[["left", "bottom"]].set_color("#e5e7eb")
            return save_fig()

        # ── AREA ───────────────────────────────────────────
        elif chart_type == "area":
            if x not in data.columns or y not in data.columns: return None
            df2 = data[[x, y]].copy()
            df2[y] = pd.to_numeric(df2[y], errors="coerce")
            df2 = df2.dropna(subset=[y]).head(200)
            if df2.empty: return None
            fig, ax = plt.subplots(figsize=(10, 5))
            xs = range(len(df2))
            ax.fill_between(xs, df2[y], alpha=0.18, color=PALETTE[0])
            ax.plot(xs, df2[y], color=PALETTE[0], linewidth=2)
            ax.set_xlabel(x, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_ylabel(y, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_title(title, color="#111827", fontsize=13, fontweight="semibold")
            step = max(1, len(df2) // 10)
            ax.set_xticks(range(0, len(df2), step))
            ax.set_xticklabels(df2[x].astype(str).iloc[::step], rotation=35, ha="right")
            ax.spines[["top", "right"]].set_visible(False)
            ax.spines[["left", "bottom"]].set_color("#e5e7eb")
            return save_fig()

        # ── PIE / DONUT ────────────────────────────────────
        elif chart_type in ("pie", "donut"):
            if x not in data.columns or y not in data.columns: return None
            df2 = data[[x, y]].copy()
            df2[y] = pd.to_numeric(df2[y], errors="coerce").fillna(0)
            df2 = df2.groupby(x, dropna=False)[y].sum().reset_index().head(10)
            if df2.empty: return None
            fig, ax = plt.subplots(figsize=(8, 6))
            wedges, texts, autotexts = ax.pie(
                df2[y], labels=df2[x].astype(str),
                autopct="%1.1f%%", colors=PALETTE[:len(df2)],
                wedgeprops={"linewidth": 2, "edgecolor": "white"},
                pctdistance=0.78, startangle=90,
            )
            for t in texts:     t.set_color("#374151"); t.set_fontsize(9)
            for t in autotexts: t.set_color("white");   t.set_fontsize(8); t.set_fontweight("bold")
            if chart_type == "donut":
                ax.add_patch(plt.Circle((0, 0), 0.55, fc="white"))
            ax.set_title(title, color="#111827", fontsize=13, fontweight="semibold", pad=16)
            return save_fig()

        # ── HISTOGRAM ─────────────────────────────────────
        elif chart_type == "histogram":
            col = x if (x and x in data.columns) else pick_num(data)
            if col is None: return None
            series = pd.to_numeric(data[col], errors="coerce").dropna()
            if series.empty: return None
            fig, ax = plt.subplots(figsize=(10, 5))
            n, bins, patches = ax.hist(series, bins=30, color=PALETTE[0],
                                        edgecolor="white", linewidth=0.5, alpha=0.85)
            for i, patch in enumerate(patches):
                patch.set_facecolor(PALETTE[i % 3])
            ax.axvline(series.mean(), color=PALETTE[3], linewidth=1.6,
                       linestyle="--", label=f"Mean: {series.mean():.4g}")
            ax.axvline(series.median(), color=PALETTE[1], linewidth=1.6,
                       linestyle="--", label=f"Median: {series.median():.4g}")
            ax.legend(framealpha=0.9)
            ax.set_xlabel(col, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_ylabel("Frequency", labelpad=8, color="#6b7280", fontsize=10)
            ax.set_title(title, color="#111827", fontsize=13, fontweight="semibold")
            ax.spines[["top", "right"]].set_visible(False)
            ax.spines[["left", "bottom"]].set_color("#e5e7eb")
            return save_fig()

        # ── SCATTER ────────────────────────────────────────
        elif chart_type == "scatter":
            if x not in data.columns or y not in data.columns: return None
            df2 = data[[x, y]].copy()
            df2[x] = pd.to_numeric(df2[x], errors="coerce")
            df2[y] = pd.to_numeric(df2[y], errors="coerce")
            df2 = df2.dropna().head(800)
            if df2.empty: return None
            fig, ax = plt.subplots(figsize=(9, 6))
            ax.scatter(df2[x], df2[y], color=PALETTE[0], alpha=0.55, s=22, edgecolors="none")
            m, b = np.polyfit(df2[x], df2[y], 1)
            xr = np.linspace(df2[x].min(), df2[x].max(), 200)
            ax.plot(xr, m * xr + b, color=PALETTE[3], linewidth=1.8,
                    linestyle="--", label="Linear trend")
            corr = df2[x].corr(df2[y])
            ax.set_title(f"{title}  (r = {corr:.3f})",
                         color="#111827", fontsize=13, fontweight="semibold")
            ax.set_xlabel(x, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_ylabel(y, labelpad=8, color="#6b7280", fontsize=10)
            ax.legend(framealpha=0.9)
            ax.spines[["top", "right"]].set_visible(False)
            ax.spines[["left", "bottom"]].set_color("#e5e7eb")
            return save_fig()

        # ── BOX ────────────────────────────────────────────
        elif chart_type == "box":
            col = y if (y and y in data.columns) else (x if (x and x in data.columns) else pick_num(data))
            if col is None: return None
            series = pd.to_numeric(data[col], errors="coerce").dropna()
            if series.empty: return None
            fig, ax = plt.subplots(figsize=(5, 7))
            ax.boxplot(series, patch_artist=True,
                       medianprops=dict(color=PALETTE[3], linewidth=2),
                       boxprops=dict(facecolor="#e0f2fe", alpha=0.8),
                       whiskerprops=dict(color=PALETTE[0]),
                       capprops=dict(color=PALETTE[0]),
                       flierprops=dict(marker="o", color=PALETTE[3], alpha=0.45, markersize=4))
            stats = series.describe()
            ax.text(0.5, -0.06,
                    f"Mean: {stats['mean']:.4g}   Median: {stats['50%']:.4g}\n"
                    f"Min: {stats['min']:.4g}   Max: {stats['max']:.4g}   Std: {stats['std']:.4g}",
                    transform=ax.transAxes, ha="center", va="top",
                    fontsize=8.5, color="#6b7280")
            ax.set_title(title, color="#111827", fontsize=13, fontweight="semibold")
            ax.set_ylabel(col, labelpad=8, color="#6b7280", fontsize=10)
            ax.set_xticks([])
            ax.spines[["top", "right"]].set_visible(False)
            ax.spines[["left", "bottom"]].set_color("#e5e7eb")
            return save_fig()

        # ── HEATMAP ────────────────────────────────────────
        elif chart_type == "heatmap":
            num_cols = data.select_dtypes(include="number").columns.tolist()
            if len(num_cols) < 2: return None
            corr = data[num_cols].corr()
            n    = len(num_cols)
            fig, ax = plt.subplots(figsize=(max(7, n), max(5, n - 1)))
            im = ax.imshow(corr.values, cmap="RdYlGn", vmin=-1, vmax=1, aspect="auto")
            ax.set_xticks(range(n)); ax.set_yticks(range(n))
            ax.set_xticklabels(num_cols, rotation=45, ha="right", fontsize=8.5)
            ax.set_yticklabels(num_cols, fontsize=8.5)
            for i in range(n):
                for j in range(n):
                    val = corr.values[i, j]
                    ax.text(j, i, f"{val:.2f}", ha="center", va="center",
                            fontsize=7.5, color="white" if abs(val) > 0.6 else "#374151")
            plt.colorbar(im, ax=ax, shrink=0.8)
            ax.set_title(title, color="#111827", fontsize=13, fontweight="semibold")
            return save_fig()

    except Exception as e:
        print(f"[chart error] {e}")
        plt.close("all")

    return None

"""##### **Analysis plan executor**"""

def execute_plan(df: pd.DataFrame, plan: Dict[str, Any], question: str) -> Dict[str, Any]:
    op       = plan.get("operation", "summary")
    target   = plan.get("target_column")
    groupby  = plan.get("groupby_column")
    agg      = plan.get("agg_func") or "mean"
    top_n    = int(plan.get("top_n") or 10)
    sort_ord = plan.get("sort_order") or "desc"
    filters  = plan.get("filters") or []
    c_type   = plan.get("chart_type", "none")
    c_x      = plan.get("chart_x")
    c_y      = plan.get("chart_y")
    c_title  = plan.get("chart_title") or "Analysis"

    wdf = apply_filters(df, filters)
    if wdf.empty:
        return {"answer": "⚠️ No rows match the applied filters.",
                "table": pd.DataFrame(), "chart_path": None}

    answer       = ""
    result_table = pd.DataFrame()
    chart_path   = None

    # ── SUMMARY ────────────────────────────────────────────
    if op == "summary":
        num_cols = wdf.select_dtypes(include="number").columns.tolist()
        stats = []
        for col in num_cols[:8]:
            s = wdf[col].dropna()
            stats.append({"Column": col, "Count": int(s.count()),
                           "Mean": round(s.mean(), 4), "Median": round(s.median(), 4),
                           "Std": round(s.std(), 4), "Min": round(s.min(), 4),
                           "Max": round(s.max(), 4)})
        result_table = pd.DataFrame(stats) if stats else pd.DataFrame(
            {"Info": [f"Rows: {len(wdf)}", f"Columns: {len(wdf.columns)}",
                      f"Total nulls: {int(wdf.isna().sum().sum())}"]}
        )
        missing = int(wdf.isna().sum().sum())
        answer  = (f"The dataset has **{len(wdf):,} rows** and **{len(wdf.columns)} columns**. "
                   f"Total null values: {missing}. "
                   f"Statistical summary of numeric columns shown below.")
        if c_type == "none" and num_cols:
            c_type = "heatmap"; c_title = "Correlation between numeric variables"
        if c_type == "heatmap":
            chart_path = make_chart("heatmap", wdf, None, None, c_title)

    # ── SCALAR OPERATIONS ──────────────────────────────────
    elif op in ("average", "sum", "count", "min", "max", "median"):
        if not target or target not in wdf.columns:
            target = pick_num(wdf)
        if target is None:
            return {"answer": "Could not find a valid numeric column.",
                    "table": pd.DataFrame(), "chart_path": None}
        num_s = pd.to_numeric(wdf[target], errors="coerce")
        ops_map = {
            "average": ("Mean",   num_s.mean()),
            "sum":     ("Sum",    num_s.sum()),
            "count":   ("Count",  int(num_s.count())),
            "min":     ("Min",    num_s.min()),
            "max":     ("Max",    num_s.max()),
            "median":  ("Median", num_s.median()),
        }
        label, value = ops_map[op]
        result_table = pd.DataFrame({"Metric": [label], "Column": [target], "Value": [value]})
        answer = f"**{label} of '{target}'**: {fmt(value)}"
        if c_type == "none":
            c_type = "histogram" if op in ("average", "median") else "bar"
            c_x, c_y = (target, None) if c_type == "histogram" else ("Metric", "Value")
        chart_path = make_chart(
            c_type,
            wdf[[target]] if c_type in ("histogram", "box") else result_table,
            c_x, c_y, c_title or f"{label} of {target}",
        )

    # ── FULL STATS ─────────────────────────────────────────
    elif op == "full_stats":
        if not target or target not in wdf.columns:
            target = pick_num(wdf)
        if target is None:
            return {"answer": "Could not find a valid numeric column.",
                    "table": pd.DataFrame(), "chart_path": None}
        s = pd.to_numeric(wdf[target], errors="coerce").dropna()
        result_table = pd.DataFrame(list({
            "Count": int(s.count()), "Mean": round(s.mean(), 4),
            "Median": round(s.median(), 4),
            "Mode": round(s.mode().iloc[0], 4) if not s.mode().empty else "N/A",
            "Std Dev": round(s.std(), 4), "Variance": round(s.var(), 4),
            "Min": round(s.min(), 4), "Q1": round(s.quantile(0.25), 4),
            "Q3": round(s.quantile(0.75), 4), "Max": round(s.max(), 4),
            "IQR": round(s.quantile(0.75) - s.quantile(0.25), 4),
            "Skewness": round(s.skew(), 4), "Kurtosis": round(s.kurt(), 4),
        }.items()), columns=["Statistic", "Value"])
        answer     = f"Full statistics for **'{target}'**."
        chart_path = make_chart("box", wdf[[target]], target, target,
                                f"Distribution of {target}")

    # ── TOP N ──────────────────────────────────────────────
    elif op == "top_n":
        sort_col = target if (target and target in wdf.columns) else pick_num(wdf)
        if sort_col is None:
            return {"answer": "No valid column found for sorting.",
                    "table": pd.DataFrame(), "chart_path": None}
        asc          = (sort_ord == "asc")
        result_table = wdf.sort_values(by=sort_col, ascending=asc).head(top_n).copy()
        label        = "lowest" if asc else "highest"
        answer       = f"Top **{top_n}** rows with the **{label}** values in **'{sort_col}'**."
        if c_type == "none":
            cat_col = pick_cat(result_table) or result_table.columns[0]
            num_col = pick_num(result_table)
            if num_col:
                c_type = "bar"; c_x = cat_col; c_y = num_col
        if c_type != "none":
            if not c_x or c_x not in result_table.columns:
                c_x = pick_cat(result_table) or result_table.columns[0]
            if not c_y or c_y not in result_table.columns:
                c_y = pick_num(result_table)
            if c_y:
                chart_path = make_chart(c_type, result_table, c_x, c_y, c_title)

    # ── GROUPBY AGG ────────────────────────────────────────
    elif op == "groupby_agg":
        if not groupby or groupby not in wdf.columns:
            groupby = pick_cat(wdf)
        if groupby is None:
            return {"answer": "No valid categorical column found for grouping.",
                    "table": pd.DataFrame(), "chart_path": None}
        if not target or target not in wdf.columns:
            target = pick_num(wdf)
        if agg not in ("mean", "sum", "count", "min", "max", "median", "std", "var"):
            agg = "count" if target is None else "mean"
        if agg == "count" or target is None:
            grouped    = wdf.groupby(groupby, dropna=False).size().reset_index(name="count")
            metric_col = "count"
        else:
            grouped    = wdf.groupby(groupby, dropna=False)[target].agg(agg).reset_index()
            grouped.columns = [groupby, f"{agg}_{target}"]
            metric_col = f"{agg}_{target}"
        if sort_ord in ("asc", "desc"):
            grouped = grouped.sort_values(metric_col, ascending=(sort_ord == "asc"))
        result_table = grouped.copy()
        answer = (f"**{agg.capitalize()} of '{target or 'count'}'** grouped by **'{groupby}'**. "
                  f"Found **{len(grouped)} groups**.")
        if c_type == "none":
            c_type = "donut" if len(grouped) <= 6 else "bar"
            c_x = groupby; c_y = metric_col
        if c_type != "none":
            if not c_x or c_x not in result_table.columns: c_x = groupby
            if not c_y or c_y not in result_table.columns: c_y = metric_col
            chart_path = make_chart(c_type, result_table, c_x, c_y, c_title)

    # ── DISTRIBUTION ───────────────────────────────────────
    elif op == "distribution":
        if not target or target not in wdf.columns:
            target = pick_num(wdf)
        if target is None:
            return {"answer": "No numeric column found for distribution analysis.",
                    "table": pd.DataFrame(), "chart_path": None}
        s = pd.to_numeric(wdf[target], errors="coerce").dropna()
        result_table = pd.DataFrame({
            "Statistic": ["Count", "Mean", "Median", "Std", "Min", "Max"],
            "Value":     [s.count(), s.mean(), s.median(), s.std(), s.min(), s.max()],
        })
        answer     = (f"Distribution of **'{target}'**: "
                      f"mean = {fmt(s.mean())}, median = {fmt(s.median())}, "
                      f"std = {fmt(s.std())}.")
        chart_path = make_chart("histogram", wdf[[target]], target, None,
                                c_title or f"Distribution of {target}")

    # ── CORRELATION ────────────────────────────────────────
    elif op == "correlation":
        num_cols = wdf.select_dtypes(include="number").columns.tolist()
        x_col = c_x if (c_x and c_x in wdf.columns) else (num_cols[0] if num_cols else None)
        y_col = c_y if (c_y and c_y in wdf.columns) else (num_cols[1] if len(num_cols) >= 2 else None)
        if not x_col or not y_col:
            if len(num_cols) >= 2:
                result_table = wdf[num_cols].corr().round(4)
                answer       = "Correlation matrix between all numeric variables."
                chart_path   = make_chart("heatmap", wdf, None, None,
                                          c_title or "Correlations")
            else:
                return {"answer": "Need at least two numeric columns for correlation.",
                        "table": pd.DataFrame(), "chart_path": None}
        else:
            tmp      = wdf[[x_col, y_col]].apply(pd.to_numeric, errors="coerce").dropna()
            corr_val = tmp[x_col].corr(tmp[y_col])
            strength = ("very strong" if abs(corr_val) > 0.8 else
                        "strong"      if abs(corr_val) > 0.6 else
                        "moderate"    if abs(corr_val) > 0.4 else "weak")
            direction = "positive" if corr_val > 0 else "negative"
            result_table = pd.DataFrame({
                "Variable X": [x_col], "Variable Y": [y_col],
                "Correlation (r)": [round(corr_val, 4)],
                "Interpretation": [f"{strength} {direction}"],
            })
            answer     = (f"Correlation between **'{x_col}'** and **'{y_col}'**: "
                          f"r = **{fmt(corr_val)}** ({strength} {direction}).")
            chart_path = make_chart("scatter", tmp, x_col, y_col,
                                    c_title or f"{x_col} vs {y_col}")

    # ── LIST UNIQUE ────────────────────────────────────────
    elif op == "list_unique":
        if not target or target not in wdf.columns:
            target = pick_cat(wdf)
        if target is None:
            return {"answer": "No categorical column found.",
                    "table": pd.DataFrame(), "chart_path": None}
        uniques      = wdf[target].dropna().astype(str).unique().tolist()
        result_table = pd.DataFrame({target: sorted(uniques)[:200]})
        answer       = f"**'{target}'** has **{len(uniques)} unique values**."
        if c_type == "none" and len(uniques) <= 15:
            counts     = wdf[target].value_counts().head(12).reset_index()
            counts.columns = [target, "count"]
            c_type     = "donut" if len(counts) <= 7 else "bar"
            chart_path = make_chart(c_type, counts, target, "count",
                                    f"Distribution of {target}")
    else:
        answer = f"Operation '{op}' not recognized."

    return {"answer": answer, "table": result_table, "chart_path": chart_path}

"""##### **LLM Narrator**"""

def generate_narrative(question: str, answer: str, table_md: str, plan: Dict) -> str:
    prompt = f"""You are an expert data analyst. Respond clearly and directly in English.

The user asked: "{question}"

Analysis result:
{answer}

Data (first rows):
{table_md[:1500]}

Operation: {plan.get('operation')} | Chart generated: {plan.get('chart_type')}

Write a NATURAL response in 3-4 sentences that:
1. Directly answers the question with the most relevant concrete data points.
2. Highlights the most interesting insight or pattern found.
3. Briefly suggests a useful follow-up question.

Do not repeat the full table. Avoid excessive markdown. Respond like an expert analyst talking to a colleague.

IMPORTANT — Number formatting rules (follow these strictly):
- NEVER use scientific notation (e.g. never write 1.23e+06 or 4.5e-3).
- Always write numbers in full: 1,230,000 instead of 1.23e+06.
- Use commas as thousands separators for large numbers: 1,450,320.
- Round decimals to 2 places maximum: 3.14, not 3.14159265.
- For very small numbers, use decimals: 0.0045, not 4.5e-3.
- For percentages, always include the % symbol: 23.4%, not 0.234.
- For currency, include the appropriate symbol if inferrable from context."""

    resp = llm.invoke([HumanMessage(content=prompt)])
    return resp.content if isinstance(resp.content, str) else str(resp.content)

"""##### **Gradio UI**"""

def handle_upload(file_obj):
    if file_obj is None:
        return "Upload a file to get started.", gr.update(visible=False)
    try:
        df = load_dataframe(file_obj.name)
        STATE["df"]       = df
        STATE["schema"]   = build_schema(df)
        STATE["filename"] = os.path.basename(file_obj.name)

        num_cols = df.select_dtypes(include="number").columns.tolist()
        cat_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
        info = (
            f"**{STATE['filename']}** loaded ✓\n\n"
            f"**{len(df):,} rows · {len(df.columns)} columns**\n\n"
            f"**Numeric:** {', '.join(num_cols[:5]) or '—'}\n\n"
            f"**Categorical:** {', '.join(cat_cols[:5]) or '—'}\n\n"
            f"**Null values:** {int(df.isna().sum().sum()):,}"
        )
        return info, gr.update(visible=True)
    except Exception as e:
        return f"Error loading file: {e}", gr.update(visible=False)


def chat_respond(message: str, history: List):
    if STATE["df"] is None:
        history = history + [
            {"role": "user",      "content": message},
            {"role": "assistant", "content": "Please upload a CSV or Excel file first so I can analyze it."},
        ]
        return history, None

    if not message.strip():
        return history, None

    try:
        plan       = get_plan(STATE["schema"], message)
        result     = execute_plan(STATE["df"], plan, message)
        table      = result["table"]
        chart_path = result["chart_path"]
        raw_answer = result["answer"]

        table_md  = table.head(20).to_markdown(index=False) if not table.empty else ""
        narrative = generate_narrative(message, raw_answer, table_md, plan)

        parts = [narrative]
        if not table.empty and len(table) > 1:
            parts.append("\n\n" + table_md)

        history = history + [
            {"role": "user",      "content": message},
            {"role": "assistant", "content": "\n\n".join(parts)},
        ]
        return history, chart_path

    except Exception as e:
        history = history + [
            {"role": "user",      "content": message},
            {"role": "assistant", "content": f"Error during analysis: {str(e)}"},
        ]
        return history, None


def on_clear():
    return WELCOME_MSG, None

CSS = """
body, .gradio-container {
    background: #ffffff !important;
    font-family: ui-sans-serif, system-ui, -apple-system, sans-serif !important;
    color: #0d0d0d !important;
}
.gradio-container { max-width: 1100px !important; margin: 0 auto !important; }

/* Sidebar */
.sidebar {
    background: #f9f9f9 !important;
    border-right: 1px solid #e5e5e5 !important;
}
.app-title {
    font-size: 15px !important;
    font-weight: 600 !important;
    color: #0d0d0d !important;
    padding: 18px 16px 14px !important;
    border-bottom: 1px solid #e5e5e5 !important;
    display: flex; align-items: center; gap: 8px;
}

/* Upload zone */
.upload-wrap label {
    border: 1.5px dashed #d1d5db !important;
    border-radius: 10px !important;
    background: #ffffff !important;
    transition: border-color .18s, background .18s !important;
}
.upload-wrap label:hover {
    border-color: #10a37f !important;
    background: #f0fdf4 !important;
}

/* Dataset info card */
.info-card {
    background: #ffffff !important;
    border: 1px solid #e5e5e5 !important;
    border-radius: 10px !important;
    padding: 14px 16px !important;
    font-size: 13px !important;
    line-height: 1.65 !important;
    color: #374151 !important;
}
.info-card strong { color: #10a37f !important; }

/* Chatbot */
.chatbot {
    border: none !important;
    background: #ffffff !important;
    font-size: 15px !important;
}
.chatbot .message.user {
    background: #f4f4f4 !important;
    border-radius: 18px 18px 4px 18px !important;
    color: #0d0d0d !important;
    border: none !important;
    font-size: 15px !important;
    max-width: 75% !important;
    padding: 12px 16px !important;
}
.chatbot .message.bot {
    background: #ffffff !important;
    border: 1px solid #e5e5e5 !important;
    border-radius: 18px 18px 18px 4px !important;
    color: #0d0d0d !important;
    font-size: 15px !important;
    max-width: 88% !important;
    padding: 14px 18px !important;
    box-shadow: 0 1px 3px rgba(0,0,0,0.06) !important;
    line-height: 1.65 !important;
}
.chatbot .message.bot table {
    width: 100% !important; border-collapse: collapse !important;
    font-size: 13px !important; margin-top: 10px !important;
}
.chatbot .message.bot table th {
    background: #f9fafb !important; color: #374151 !important;
    padding: 8px 12px !important; font-weight: 600 !important;
    border-bottom: 1px solid #e5e7eb !important; text-align: left !important;
}
.chatbot .message.bot table td {
    padding: 7px 12px !important;
    border-bottom: 1px solid #f3f4f6 !important; color: #374151 !important;
}
.chatbot .message.bot table tr:last-child td { border-bottom: none !important; }
.chatbot .message.bot table tr:hover td { background: #f9fafb !important; }

/* Input */
.input-row {
    border-top: 1px solid #e5e5e5 !important;
    background: #ffffff !important;
    padding: 12px 4px 4px !important;
}
.input-row textarea {
    background: #f9f9f9 !important;
    border: 1px solid #d1d5db !important;
    border-radius: 12px !important;
    color: #0d0d0d !important;
    font-size: 15px !important;
    padding: 13px 16px !important;
    resize: none !important;
    line-height: 1.5 !important;
    transition: border-color .18s, box-shadow .18s !important;
}
.input-row textarea:focus {
    border-color: #10a37f !important;
    box-shadow: 0 0 0 3px rgba(16,163,127,0.12) !important;
    background: #ffffff !important;
    outline: none !important;
}

/* Buttons */
.btn-send {
    background: #10a37f !important; color: white !important;
    border: none !important; border-radius: 10px !important;
    padding: 13px 22px !important; font-size: 14px !important;
    font-weight: 600 !important; min-width: 88px !important;
    transition: background .18s !important;
}
.btn-send:hover { background: #0e9268 !important; }
.btn-clear {
    background: transparent !important; color: #9ca3af !important;
    border: 1px solid #e5e7eb !important; border-radius: 10px !important;
    padding: 13px 14px !important; font-size: 13px !important;
    transition: all .18s !important;
}
.btn-clear:hover {
    background: #f9fafb !important; color: #6b7280 !important;
}

/* Chart */
.chart-panel {
    background: #ffffff !important; border: 1px solid #e5e5e5 !important;
    border-radius: 12px !important; overflow: hidden !important;
    margin-top: 4px !important;
}
.chart-panel img { width: 100% !important; border-radius: 10px !important; }

/* Tabs */
.tab-nav {
    background: #f9f9f9 !important;
    border-bottom: 1px solid #e5e5e5 !important;
    padding: 0 8px !important;
}
.tab-nav button {
    color: #6b7280 !important; font-size: 13px !important;
    font-weight: 500 !important; padding: 10px 16px !important;
    border-bottom: 2px solid transparent !important;
    background: transparent !important; border-radius: 0 !important;
}
.tab-nav button.selected {
    color: #10a37f !important;
    border-bottom: 2px solid #10a37f !important;
}

/* Tips */
.tips-box {
    font-size: 12.5px !important; color: #6b7280 !important;
    line-height: 1.7 !important; padding: 10px 14px 14px !important;
}
.tips-box b { color: #374151 !important; }

/* Scrollbar */
::-webkit-scrollbar { width: 5px; height: 5px; }
::-webkit-scrollbar-track { background: #f9fafb; }
::-webkit-scrollbar-thumb { background: #d1d5db; border-radius: 3px; }
::-webkit-scrollbar-thumb:hover { background: #9ca3af; }
"""

WELCOME_MSG = [
    {
        "role": "assistant",
        "content": (
            "Hi! I'm your AI data analyst.\n\n"
            "Upload a **CSV or Excel** file in the left panel, then ask me anything about your data. I can:\n\n"
            "- Calculate averages, sums, min/max, medians\n"
            "- Group and compare categories\n"
            "- Show distributions and correlations\n"
            "- Generate charts automatically (bar, line, pie, scatter, histogram, heatmap, and more)\n"
            "- Provide full statistical summaries\n\n"
            "What would you like to analyze today?"
        ),
    }
]

EXAMPLES = [
    "Give me a summary of the dataset",
    "What is the average sales value?",
    "Show the distribution of prices",
    "Top 10 rows by highest value",
    "Group by category and sum",
    "Correlation between variables",
    "How many unique values are there?",
    "Full statistics for a column",
]

with gr.Blocks(css=CSS, title="Data Analyst · AI") as demo:

    with gr.Row(equal_height=True):

        # ── SIDEBAR ─────────────────────────────────────────
        with gr.Column(scale=1, min_width=260, elem_classes=["sidebar"]):

            gr.HTML(
                '<div class="app-title">'
                '<svg width="17" height="17" viewBox="0 0 24 24" fill="none" '
                'stroke="#10a37f" stroke-width="2" stroke-linecap="round">'
                '<polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>'
                ' Data Analyst</div>'
            )

            gr.HTML('<div style="padding:12px 14px 6px;font-size:11px;font-weight:600;'
                    'color:#9ca3af;letter-spacing:.06em;text-transform:uppercase;">Dataset</div>')

            file_input = gr.File(
                label="Upload CSV or Excel",
                file_types=[".csv", ".xlsx", ".xls"],
                elem_classes=["upload-wrap"],
            )

            file_info = gr.Markdown(
                value="*Upload a file to get started...*",
                elem_classes=["info-card"],
            )


        # ── MAIN PANEL ──────────────────────────────────────
        with gr.Column(scale=3):

            with gr.Tabs():

                # ── CHAT TAB ──────────────────────────────────
                with gr.Tab("Chat"):
                    chatbot = gr.Chatbot(
                        value=WELCOME_MSG,
                        label="",
                        height=500,
                        show_copy_button=True,
                        render_markdown=True,
                        bubble_full_width=False,
                        type="messages",
                        elem_classes=["chatbot"],
                        avatar_images=(
                            None,
                            "https://api.dicebear.com/8.x/bottts-neutral/svg?seed=analyst&backgroundColor=b6e3f4",
                        ),
                    )

                    with gr.Row(elem_classes=["input-row"]):
                        chat_input = gr.Textbox(
                            placeholder="Ask something about your data…",
                            show_label=False,
                            lines=1,
                            max_lines=5,
                            scale=8,
                        )
                        send_btn = gr.Button(
                            "Send ↗",
                            scale=1,
                            variant="primary",
                            elem_classes=["btn-send"],
                        )
                        clear_btn = gr.Button(
                            "🗑",
                            scale=0,
                            elem_classes=["btn-clear"],
                        )

                # ── CHART TAB ─────────────────────────────────
                with gr.Tab("Chart"):
                    chart_output = gr.Image(
                        label="",
                        show_label=False,
                        show_download_button=True,
                        height=490,
                        elem_classes=["chart-panel"],
                    )
                    gr.HTML(
                        '<p style="text-align:center;color:#9ca3af;font-size:12px;padding:10px 0 2px;">'
                        'Chart is generated automatically with each analysis</p>'
                    )

                # ── SCHEMA TAB ────────────────────────────────
                with gr.Tab("Schema"):
                    schema_md = gr.Markdown(
                        value="*Upload a file to inspect the dataset schema.*",
                        elem_classes=["info-card"],
                    )

    # ── Event wiring ──────────────────────────────────────────

    def on_upload(f):
        info, vis  = handle_upload(f)
        schema_txt = STATE["schema"] if STATE["schema"] else "*No data loaded yet.*"
        return info, schema_txt, vis

    file_input.change(
        fn=on_upload,
        inputs=file_input,
        outputs=[file_info, schema_md, chart_output],
    )

    def on_send(msg, hist):
        if not msg.strip():
            return hist, None, ""
        new_hist, chart = chat_respond(msg, hist)
        return new_hist, chart, ""

    send_btn.click(
        fn=on_send,
        inputs=[chat_input, chatbot],
        outputs=[chatbot, chart_output, chat_input],
    )
    chat_input.submit(
        fn=on_send,
        inputs=[chat_input, chatbot],
        outputs=[chatbot, chart_output, chat_input],
    )
    clear_btn.click(fn=on_clear, outputs=[chatbot, chart_output])

demo.launch(debug=False, share=True, show_error=True)